name: overwin_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  intl: ^0.20.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  app_links: ^3.4.5
  top_snackbar_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/overwin.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/overwin.png"
    background_color: "#000000"
    theme_color: "#1C67FF"
  windows:
    generate: true
    image_path: "assets/icons/overwin.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/overwin.png"
